### ISSUE TITLE
run in my_way_home

### ISSUE THREAD

**Issue by WangChen100** [Swirler/Deep-Reinforcement-Learning-applied-to-DOOM#3]
Hi, it seems that in this code the agent cannot learn to navigation in my_way_home, does it?

**Comment by Chaoukia** [comment]
Hello, sorry for the late answer, we were very busy lately.

You're right about my_way_home, we've tried curiosity with an A3C backbone
briefly but did not succeed in making the agent learn. If you can make it,
we would be very Happy to learn How you did it.

Thank you for your interest in our work.

Best regards,

Ayman

**Comment by WangChen100** [comment]
Hi Ayman.
I find a successful repository and fork it from others'. 

https://github.com/WangChen100/a2c_curiosity_vizdoom_tf

Compared with our implementation, the codes in this repository include lots of tricks, such as L2 regularizer, special calculation method on information entropy and so on.

To be honest, this repository deserve a mention and a review.

**Comment by Chaoukia** [comment]
Hi Wang, thank you for the repository, I'll take a loot at it. 
In fact, our aim was to see how curiosity would behave when put in an environment requiring a lot of exploration like "my way home", but we did not investigate in depth why it didn't work and it is definitely something worth looking at.
