### ISSUE TITLE
Generate maze in Doom

### ISSUE THREAD

**Issue by WangChen100** [Swirler/Deep-Reinforcement-Learning-applied-to-DOOM#4]
Hi, Swirler. Do you have some ideas about how to generate mazes in doom by ourselves?

Actually, I could build a wad file about maze with omgifol module. Unfortunately, I don't know how to set a goal in maze. Would you please do me a favour?

Waiting for your reply. Thank you very very much.

**Comment by Chaoukia** [comment]
Hello WangChen! Sorry for the late answer. Actually, we didn't work on the maze part that much, and didn't  create new wad files for customized Doom scenarios, we only used default ones. So for now we are not able to give you an answer, however if we make some further progress on the project requiring customized wad files, we'll let you know.
Thank you again for your interest.

**Comment by WangChen100** [comment]
Hello Chaoukia! Thank you for your reply. I solve the problem somehow. Hope to communicate with you on reinforcement learning in the future. Thank you all the same.
